// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: end_server.proto

package generatedCode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body             string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	SenderUsername   string `protobuf:"bytes,2,opt,name=senderUsername,proto3" json:"senderUsername,omitempty"`
	ReceiverUsername string `protobuf:"bytes,3,opt,name=receiverUsername,proto3" json:"receiverUsername,omitempty"`
}

func (x *EndServerMessage) Reset() {
	*x = EndServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_end_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndServerMessage) ProtoMessage() {}

func (x *EndServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_end_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndServerMessage.ProtoReflect.Descriptor instead.
func (*EndServerMessage) Descriptor() ([]byte, []int) {
	return file_end_server_proto_rawDescGZIP(), []int{0}
}

func (x *EndServerMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EndServerMessage) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *EndServerMessage) GetReceiverUsername() string {
	if x != nil {
		return x.ReceiverUsername
	}
	return ""
}

type EndServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *EndServerResponse) Reset() {
	*x = EndServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_end_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndServerResponse) ProtoMessage() {}

func (x *EndServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_end_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndServerResponse.ProtoReflect.Descriptor instead.
func (*EndServerResponse) Descriptor() ([]byte, []int) {
	return file_end_server_proto_rawDescGZIP(), []int{1}
}

func (x *EndServerResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_end_server_proto protoreflect.FileDescriptor

var file_end_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x10, 0x45, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b,
	0x0a, 0x11, 0x45, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x54, 0x0a, 0x17, 0x45,
	0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x11, 0x2e, 0x45, 0x6e, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x45, 0x6e,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x41, 0x64, 0x61, 0x72, 0x73, 0x68, 0x2d, 0x4b, 0x6d, 0x74, 0x2f, 0x45, 0x6e, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_end_server_proto_rawDescOnce sync.Once
	file_end_server_proto_rawDescData = file_end_server_proto_rawDesc
)

func file_end_server_proto_rawDescGZIP() []byte {
	file_end_server_proto_rawDescOnce.Do(func() {
		file_end_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_end_server_proto_rawDescData)
	})
	return file_end_server_proto_rawDescData
}

var file_end_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_end_server_proto_goTypes = []interface{}{
	(*EndServerMessage)(nil),  // 0: EndServerMessage
	(*EndServerResponse)(nil), // 1: EndServerResponse
}
var file_end_server_proto_depIdxs = []int32{
	0, // 0: EndServerMessageService.ReceiveMessage:input_type -> EndServerMessage
	1, // 1: EndServerMessageService.ReceiveMessage:output_type -> EndServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_end_server_proto_init() }
func file_end_server_proto_init() {
	if File_end_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_end_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_end_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_end_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_end_server_proto_goTypes,
		DependencyIndexes: file_end_server_proto_depIdxs,
		MessageInfos:      file_end_server_proto_msgTypes,
	}.Build()
	File_end_server_proto = out.File
	file_end_server_proto_rawDesc = nil
	file_end_server_proto_goTypes = nil
	file_end_server_proto_depIdxs = nil
}
